package org.ssupstart.bookmanagement.dummylocalentity;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;
import org.hibernate.validator.constraints.UniqueElements;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
public class Book {

    //VIMP ID should be in long instead of Integer
    private Long id;  //autoGenerate we can use Id annotation for proper entity class

    @NotBlank(message = "Title is required")
    private String title;

    @NotBlank(message = "Author is required")
    private String author;

    @NotBlank(message = "ISBN is required")
    @UniqueElements
    private String isbn;

    private LocalDate publishedDate;

    private LocalDateTime createdAt; // autoGenerated we can use cuurentTimeStamp annotation for this
}
